#!/usr/bin/env python3
"""
Figure flaming generated by HiST program
Michael Hirsch
"""
from numpy import isclose
from numpy.testing import assert_allclose
from sys import argv
import h5py
#
from histfeas.main_hist import doSim

def hist_figure():
    Phi0,Phifit =doSim(ParamFN=regXLS,
                  makeplot=['fwd','optim'],
                  timeInds=timeInds,
                  overrides = overrides, #{'minev': minev,'filter':filt, 'fwdguess':fwdguess, 
				                    #'fitm':fitm,'cam':cam,'camx':acx,'ell':ell,'Jfwd':influx},
                  progms = outdir,
                  x1d=[None],
                  vlim = vlim,
                  animtime=None,
                  cmd = ' '.join(argv),
                  verbose=0
                  )

    return Phi0,Phifit


if __name__ == '__main__':
    regXLS='in/2cam_flame.xlsx'
    timeInds=[1,3]
    outdir='out/rev2_flame2'
    x1d = 1.
    vlim = {'p':[0,5,90,300,5e7,5e9], 'j':[1e5,1e6], 'b':[0,3e3]}
    overrides = {'ell':False}
    
    Phi0,Phifit=hist_figure()