#!/usr/bin/env python3
"""
Figure flaming generated by HiST program
Michael Hirsch
"""
from sys import argv
from matplotlib.pyplot import show
#
from histfeas.main_hist import doSim
from histfeas.loadAnalyze import readresults,findxlsh5

def hist_figure():
    Phi0,Phifit =doSim(ParamFN=regXLS,
                  makeplot=['fwd','optim','png','h5'],
                  timeInds=timeInds,
                  overrides = overrides, #{'minev': minev,'filter':filt, 'fwdguess':fwdguess,
				                    #'fitm':fitm,'cam':cam,'camx':acx,'ell':ell,'Jfwd':influx},
                  progms = outdir,
                  x1d=[None],
                  vlim = vlim,
                  animtime=None,
                  cmd = ' '.join(argv),
                  verbose=0
                  )

    return Phi0,Phifit


if __name__ == '__main__':
    from argparse import ArgumentParser
    p = ArgumentParser(description='flaming figure plotter')
    p.add_argument('--load',help='load without recomputing',action='store_true')
    p.add_argument('-m','--makeplot',help='plots to make',default=[],nargs='+')
    p = p.parse_args()

    regXLS='in/2cam_flame.xlsx'
    timeInds=[1,3]
    outdir='out/rev2_flame2'
    x1d = 1.
    vlim = {'p':[0,5,90,300,5e7,5e9], 'j':[5e4,4e5], 'b':[0,3e3]}
    overrides = {'ell':False}

    if not p.load:
        print('running Hist program -- will write png and h5 to ' + outdir)
        Phi0,Phifit=hist_figure()


    h5list,xlsfn = findxlsh5(outdir)
    readresults(h5list,xlsfn,overrides,p.makeplot)

    if 'show' in p.makeplot:
        show()