#!/usr/bin/env python
"""
Figures of flaming aurora generated by HiST program

intended for use with in/ files including:
*_flame.ini
*_impulse.ini
*_trans.ini

Flaming Aurora 2 cameras:
python FigureMaker.py in/2cam_flame.ini out/2cam_flame

Translating Aurora 2 cameras:
python FigureMaker.py in/2cam_trans.ini out/2cam_trans

Impulse Aurora (for testing):
python FigureMaker.py in/2cam_impulse.ini out/2cam_impulse

"""
from histfeas import userinput, hist_figure
from histfeas.loadAnalyze import readresults,findxlsh5

P = userinput()

P['x1d'] = 1.
P['vlim'] = {'p':[5e7,8e8],  'p1d':(5e7,2e9),
             'j':[1e3,1.1e5],'j1d':(1e3,8e5),
             'b':[0,1.5e3],
             'x':(-1.5,4.5), 'z':(90,300)}
#%% compute
if not P['load']:
    hist_figure(P)
#%% load
h5list,xlsfn = findxlsh5(P['outdir'])
readresults(h5list,P)
