#!/usr/bin/env python3
"""
Figure flaming generated by HiST program
Michael Hirsch
"""
from __future__ import division,absolute_import
from pathlib2 import Path
from sys import argv
from matplotlib.pyplot import show
#
import seaborn as sns
sns.color_palette("cubehelix")
sns.set(context='paper', style='whitegrid',font_scale=1.5,#2,
        rc={'image.cmap': 'cubehelix_r'})
#
from histfeas.main_hist import doSim
from histfeas.loadAnalyze import readresults,findxlsh5

def hist_figure(xlsreg,makecomp):
    Phi0,Phifit =doSim(ParamFN=xlsreg,
                  makeplot=makecomp,
                  timeInds=timeInds,
                  overrides = overrides, #{'minev': minev,'filter':filt, 'fwdguess':fwdguess,
				                    #'fitm':fitm,'cam':cam,'camx':acx,'ell':ell,'Jfwd':influx},
                  odir = outdir,
                  x1d=x1d,
                  vlim = vlim,
                  animtime=None,
                  cmd = ' '.join(argv),
                  verbose=0
                  )

    return Phi0,Phifit


if __name__ == '__main__':
    from argparse import ArgumentParser
    p = ArgumentParser(description='flaming figure plotter')
    p.add_argument('--load',help='load without recomputing',action='store_true')
    p.add_argument('-c','--compute',help='plot modes to compute the first time  e.g. "realvid png"  or  "optim png h5"',nargs='+',default=['optim','png','h5'])
    p.add_argument('-m','--makeplot',help='plots to load and make (must have been first computed via -c)',default=[],nargs='+')
    p.add_argument('--ell',help='compute projection matrix',action='store_true')
    p.add_argument('-v','--verbose',help='verbosity',action='count',default=0)
    p.add_argument('-f','--frames',help='time steps to use',type=int,nargs='+')
    p.add_argument('-o','--outdir',help='output directory',default='out/realtry')
    p = p.parse_args()

    xlsreg='in/apr14.xlsx'
    outdir = Path(p.outdir)
    timeInds=p.frames
    x1d = None
    vlim = {'p':[-3,3,90,400,5e4,5e5,5e4,5e5], 'j':[10,200, 10,200],
            'b':[0,750]}
    overrides = {'ell':p.ell}

    if not p.load:
        print('running HiSTfeas program -- will write png and h5 to {}'.format(outdir))
        Phi0,Phifit = hist_figure(xlsreg,p.compute)

    h5list,xlsfn = findxlsh5(outdir)
    readresults(h5list,xlsfn,vlim,x1d,overrides,p.makeplot,p.verbose)

    if 'show' in p.makeplot:
        show()