#!/usr/bin/env python3
"""
Figure flaming generated by HiST program
Michael Hirsch
"""
from tempfile import gettempdir
from histfeas import Path
from sys import argv
from matplotlib.pyplot import show
#
import seaborn as sns
sns.color_palette("cubehelix")
sns.set(context='paper', style='whitegrid',font_scale=2,
        rc={'image.cmap': 'cubehelix_r'})
#
from histfeas.main_hist import doSim
from histfeas.loadAnalyze import readresults,findxlsh5

def hist_figure(xlsreg):
    Phi0,Phifit =doSim(ParamFN=xlsreg,
                  makeplot=p.makeplot,
                  timeInds=timeInds,
                  overrides = overrides, #{'minev': minev,'filter':filt, 'fwdguess':fwdguess,
				                    #'fitm':fitm,'cam':cam,'camx':acx,'ell':ell,'Jfwd':influx},
                  odir = outdir,
                  x1d=x1d,
                  vlim = vlim,
                  animtime=None,
                  cmd = ' '.join(argv),
                  verbose=0
                  )

    return Phi0,Phifit


if __name__ == '__main__':
    from argparse import ArgumentParser
    p = ArgumentParser(description='flaming figure plotter')
    p.add_argument('--load',help='load without recomputing',action='store_true')
    p.add_argument('-m','--makeplot',help='plots to make',default=['fwd','optim','png','h5'],nargs='+')
    p.add_argument('--cx',help='override cam positions (must specify all)',nargs='+',type=float)
    p.add_argument('-v','--verbose',help='verbosity',action='count',default=0)
    p.add_argument('-f','--frames',help='time steps to use',type=int)#default=(1,3))
    p.add_argument('-o','--outdir',help='output directory',default=Path(gettempdir()) / 'out/impulse')
    p = p.parse_args()

    xlsreg='in/2cam_impulse.xlsx'
    outdir = Path(p.outdir)
    timeInds=p.frames

    x1d = [1,1,1]
    vlim = {'p':[-1.5,4.5,90,300,5e7,8e8,5e7,2e9], 'j':[1e3,1.1e5, 1e3,8e5],
            'b':[0, 2000]}
    overrides = {'camx':p.cx}

    if not p.load:
        print('running HiSTfeas program -- will write png and h5 to {}'.format(outdir))
        Phi0,Phifit=hist_figure(xlsreg)


    h5list,xlsfn = findxlsh5(outdir)
    readresults(h5list,xlsfn,vlim,x1d,overrides,p.makeplot,p.verbose)

    if 'show' in p.makeplot:
        show()
