#!/usr/bin/env python
"""
Figures of flaming aurora generated by HiST program
"""
from tempfile import gettempdir
from histfeas import Path
from sys import argv

def hist_figure(xlsreg):
    from histfeas.main_hist import doSim

    doSim(ParamFN=xlsreg,
                  makeplot=['fwd','optim','png','h5'],
                  timeInds=timeInds,
                  overrides = overrides, #{'minev': minev,'filter':filt, 'fwdguess':fwdguess,
				                    #'fitm':fitm,'cam':cam,'camx':acx,'ell':ell,'Jfwd':influx},
                  odir = outdir,
                  x1d=x1d,
                  vlim = vlim,
                  animtime=None,
                  cmd = ' '.join(argv),
                  verbose=0
                  )



if __name__ == '__main__':
    from argparse import ArgumentParser
    p = ArgumentParser(description='flaming figure plotter')
    p.add_argument('--load',help='load without recomputing',action='store_true')
    p.add_argument('-m','--makeplot',help='plots to make',default=[],nargs='+')
    p.add_argument('-L','--ell',help='compute projection matrix',action='store_true')
    p.add_argument('-v','--verbose',help='verbosity',action='count',default=0)
    p.add_argument('-f','--frames',help='time steps to use',nargs='+',type=int)#default=(1,3))
    p.add_argument('-o','--outdir',help='output directory',default=Path(gettempdir())/'out/rev2_flame2')
    p = p.parse_args()

    if not 'show' in p.makeplot:
        import matplotlib
        matplotlib.use('Agg')
        print(matplotlib.get_backend())
    #
    from matplotlib.pyplot import show
    #
    import seaborn as sns
    sns.color_palette("cubehelix")
    sns.set(context='paper', style='whitegrid',font_scale=2,
            rc={'image.cmap': 'cubehelix_r'})

    xlsreg='in/2cam_flame.ini'
    outdir = Path(p.outdir).expanduser()

    if len(p.frames)==2:
        timeInds=range(p.frames[0],p.frames[1])
    elif len(p.frames)==3:
        timeInds=range(p.frames[0],p.frames[1],p.frames[2])
    else:
        timeInds=p.frames

    x1d = [1,1,1]
    vlim = {'p':[-1.5,4.5,90,300,5e7,8e8,5e7,2e9], 'j':[1e3,1.1e5, 1e3,8e5],
            'b':[0,1.5e3]}
    overrides = {'ell':p.ell}

    if not p.load:
        print('running HiSTfeas program -- will write png and h5 to {}'.format(outdir))
        hist_figure(xlsreg)

    from histfeas.loadAnalyze import readresults,findxlsh5
    h5list,xlsfn = findxlsh5(outdir)
    readresults(h5list,xlsfn,vlim,x1d,overrides,p.makeplot,p.verbose)

    if 'show' in p.makeplot:
        show()
