#!/usr/bin/env python
"""
Figures of flaming aurora generated by HiST program

intended for use with in/{2,3}cam_flame.ini
"""
from histfeas import userinput, hist_figure

if __name__ == '__main__':
    from histfeas.loadAnalyze import readresults,findxlsh5
    P = userinput(ini='../in/2cam_flame.ini',outdir='out/2camflame')

    P['x1d'] = 1.
    P['vlim'] = {'p':[5e7,8e8],  'p1d':(5e7,2e9),
                 'j':[1e3,1.1e5],'j1d':(1e3,8e5),
                 'b':[0,1.5e3],
                 'x':(-1.5,4.5), 'z':(90,300)}
#%% compute
    if not P['load']:
        hist_figure(P)
#%% load
    h5list,xlsfn = findxlsh5(P['outdir'])
    readresults(h5list,P)
